# version: '3'

# services:
#   nest:
#     build: .
#     ports:
#       - "3000:3000"
#     environment:
#       NODE_ENV: development
#       MYSQL_HOST: mysql
#       MYSQL_PORT: 3306
#       MYSQL_USER: root
#       MYSQL_PASSWORD: null
#       MYSQL_DATABASE: freelancerproject-user
#       MONGODB_URI: mongodb://mongodb:27017/UserFiver
#     depends_on:
#       - mysql
#       - mongodb

#   mysql:
#     image: mysql:5.7
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_DATABASE: freelancerproject-user
#       MYSQL_USER: root
#       MYSQL_PASSWORD: null
#       # MYSQL_ROOT_PASSWORD: password

#   mongodb:
#     image: mongo:4.4
#     ports:
#       - "27017:27017"
#     environment:
#       # MONGO_INITDB_ROOT_USERNAME: root
#       # MONGO_INITDB_ROOT_PASSWORD: password