version: '3.9'
services:
  user-service:
    container_name: nest-user-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
      - phpmyadmin
      - mongodb
    networks:
      - my-network
  
  mysql:
    container_name: mysql
    image: mariadb:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: freelancerproject-user
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3307:3306"
    volumes:
      - type: bind
        source: c:/xampp/mysql/data/freelancerproject@002duser
        target: /var/lib/mysql
    networks:
      - my-network

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    hostname: phpmyadmin
    # restart: always
    environment:
        - PMA_HOST=mysql
        - PMA_USER=root
    ports:
      - 8000:80
    depends_on:
      - mysql
    networks:
      - my-network

  mongodb:
    container_name: mongodb
    image: mongo:latest
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ''
      MONGO_INITDB_ROOT_PASSWORD: ''
      MONGO_INITDB_DATABASE: UserFiver
    ports:
      - "27017:27017"
    networks:
      - my-network
        
networks:
  my-network:
    driver: bridge

# volumes:
#   mysql-data:
#   mongodb-data:


    # environment:
    #   NODE_ENV: development
    #   # MYSQL_HOST: mysql
    #   # MYSQL_PORT: 3306
    #   # MYSQL_USER: root
    #   # MYSQL_PASSWORD: ''
    #   # MYSQL_DATABASE: freelancerproject-user
    #   # MONGODB_HOST: mongodb
    #   # MONGODB_PORT: 27017
    #   # MONGODB_USER: ''
    #   # MONGODB_PASSWORD: ''
    #   # MONGODB_DATABASE: UserFiver
    # ports:
    #   - "8088:8088"


# version: '3.8'

# services:
#   nest:
#     build: .
#     ports:
#       - "8080:8080"
#     environment:
#       NODE_ENV: development
#       MYSQL_HOST: mysql
#       MYSQL_PORT: 3306
#       MYSQL_USER: root
#       MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#       MYSQL_DATABASE: freelancerproject-user
#       MONGODB_URI: mongodb://mongodb:27017/UserFiver
#     depends_on:
#       - mysql
#       - mongodb

#   mysql:
#     image: mysql:5.7
#     ports:
#       - "3307:3306"
#     # environment:
#     #   MYSQL_DATABASE: freelancerproject-user
#       # MYSQL_USER: root
#       # # MYSQL_ROOT_PASSWORD: ''
#       # MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#       # MYSQL_ROOT_PASSWORD: password

#   mongodb:
#     image: mongo:4.4
#     ports:
#       - "27017:27017"
#     # environment:
#       # MONGO_INITDB_ROOT_USERNAME: admin
#       # MONGO_INITDB_ROOT_PASSWORD: 
#     restart: always


  # volumes:
  #   mysql-data:
  #     driver: local
  #     driver_opts:
  #       type: none
  #       o: bind
  #       device: c:/xampp/mysql/data/freelancerproject@002duser